import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useIPFSContext } from '../context/ipfs'
import Footer from '../components/footer'

const Home: NextPage = () => {
  const { id: nodeId } = useIPFSContext()

  return (
    <div className={styles.container}>
      <Head>
        <title>IPFS Playgound</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://ipfs.tech">IPFS</a> Playground
        </h1>

        <p className={styles.description}>
          This page is running a a js-ipfs node in the browser using the{' '}
          <a href="https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-core">
            ipfs-core
          </a>{' '}
          package. <br />
          Access the{' '}
          <a href="https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-core">
            Core API
          </a>{' '}
          via
          <code className={styles.code}>window.ipfs</code>
          <br />
          Node ID: <code>{nodeId?.id.toString()}</code>
        </p>

        <div className={styles.grid}>
          <Link href="/peers">
            <a className={styles.card}>
              <h2>Peers &rarr;</h2>
              <p>See the current IPFS node's peers </p>
            </a>
          </Link>

          <Link href="/upload">
            <a className={styles.card}>
              <h2>Upload &rarr;</h2>
              <p>Upload a file</p>
            </a>
          </Link>

          <Link href="/ipns">
            <a className={styles.card}>
              <h2>IPNS</h2>
              <p>Publish and resolve IPNS names</p>
            </a>
          </Link>

          {/* <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>
      <Footer />
    </div>
  )
}

export default Home
